version: '3'
services:
  app:
    build:
      dockerfile: ./post-api.dockerfile
      context: .
    container_name: post-api
    networks:
      - post-network
    ports:
      - "8080:8080"
  web:
    build:
      dockerfile: ./post-web.dockerfile
      context: .
    container_name: post-web
    ports:
      - "80:80"
    networks:
      - post-network
networks:
  post-network:
    driver: bridge
